export const DOCS_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Documentation | vnsh</title>
  <meta name="description" content="Learn how to share durable knowledge between people, Claude Code, Codex, Cursor and other AI Agents with vnsh.">
  <link rel="canonical" href="https://vnsh.dev/docs">
  <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect fill='%234f66e8' width='32' height='32' rx='8'/%3E%3Cpath d='M8 10l6 13 10-13' fill='none' stroke='white' stroke-width='4' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E">
  <meta name="theme-color" content="#f7f5ef">
  <style>
    :root{--paper:#f7f5ef;--card:#fffefa;--soft:#eeece4;--ink:#20211f;--muted:#686961;--line:#dcd9cf;--blue:#4f66e8;--blue-wash:#edf0ff;--code:#292a27;--sans:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--mono:"SFMono-Regular",Consolas,"Liberation Mono",monospace}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.65 var(--sans)}a{color:inherit}.top{position:sticky;top:0;z-index:20;border-bottom:1px solid rgba(220,217,207,.85);background:rgba(247,245,239,.92);backdrop-filter:blur(14px)}.top-inner{max-width:1240px;height:66px;margin:auto;padding:0 28px;display:flex;align-items:center;gap:28px}.brand{text-decoration:none;font-size:20px;font-weight:760;letter-spacing:-.05em}.brand i{color:var(--blue);font-style:normal}.top-label{padding-left:22px;border-left:1px solid var(--line);font-size:13px;color:var(--muted)}.top-links{display:flex;align-items:center;gap:22px;margin-left:auto}.top-links a{text-decoration:none;color:var(--muted);font-size:13px;font-weight:600}.top-links a:hover{color:var(--ink)}.top-links .start{height:38px;padding:0 16px;display:inline-flex;align-items:center;border-radius:999px;background:var(--ink);color:white}
    .layout{max-width:1240px;margin:auto;padding:0 28px;display:grid;grid-template-columns:220px minmax(0,760px) 1fr;gap:54px}.side{position:sticky;top:96px;align-self:start;padding:40px 0}.side-label{margin:22px 0 8px;color:#93938b;font-size:10px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.side a{display:block;padding:5px 0;text-decoration:none;color:var(--muted);font-size:13px}.side a:hover{color:var(--blue)}
    main{padding:78px 0 110px;min-width:0}.eyebrow{color:var(--blue);font-size:12px;font-weight:800;letter-spacing:.11em;text-transform:uppercase}.hero h1{max-width:680px;margin:13px 0 20px;font-size:clamp(2.8rem,6vw,4.8rem);line-height:1;letter-spacing:-.06em}.hero>p{max-width:650px;color:var(--muted);font-size:18px}.quick-choice{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:36px 0 72px}.choice{display:block;padding:20px;border:1px solid var(--line);border-radius:16px;background:var(--card);text-decoration:none}.choice:hover{border-color:#bdc5f4;box-shadow:0 10px 30px rgba(54,56,48,.07)}.choice b{display:block;margin-bottom:4px;font-size:15px}.choice span{color:var(--muted);font-size:13px}.choice.primary{background:var(--blue-wash);border-color:#cbd1fb}
    section{scroll-margin-top:96px;padding:12px 0 58px;border-top:1px solid var(--line)}.section-kicker{display:inline-block;margin-top:25px;color:var(--blue);font-size:11px;font-weight:800;letter-spacing:.09em;text-transform:uppercase}h2{margin:8px 0 12px;font-size:30px;line-height:1.2;letter-spacing:-.035em}h3{margin:30px 0 8px;font-size:18px;letter-spacing:-.02em}p{margin:8px 0;color:var(--muted)}strong{color:var(--ink)}
    .steps{counter-reset:step;display:grid;gap:12px;margin:24px 0}.step{counter-increment:step;display:grid;grid-template-columns:34px 1fr;gap:13px;padding:17px;border:1px solid var(--line);border-radius:14px;background:var(--card)}.step:before{content:counter(step);width:28px;height:28px;display:grid;place-items:center;border-radius:50%;background:var(--blue-wash);color:var(--blue);font-size:12px;font-weight:800}.step b{display:block}.step p{margin:2px 0 0;font-size:13px}
    pre{margin:16px 0;padding:18px 20px;overflow:auto;border-radius:13px;background:var(--code);color:#f5f4ef;font:13px/1.7 var(--mono)}code{font-family:var(--mono)}p code,li code,td code{padding:2px 5px;border-radius:5px;background:var(--soft);color:#484944;font-size:.88em}.note{margin:20px 0;padding:16px 18px;border-radius:12px;background:var(--blue-wash);border-left:3px solid var(--blue);color:#4c557e;font-size:14px}.note strong{color:#353e70}.warning{background:#fff7ec;border-left-color:#cf7b36;color:#735238}.warning strong{color:#5a3c25}
    .mode-grid,.tool-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:22px 0}.mode,.tool{padding:20px;border:1px solid var(--line);border-radius:14px;background:var(--card)}.mode h3,.tool h3{margin:0 0 7px}.mode p,.tool p{font-size:13px}.badge{display:inline-flex;padding:3px 8px;border-radius:999px;background:var(--soft);color:var(--muted);font-size:10px;font-weight:800;letter-spacing:.07em;text-transform:uppercase}.badge.blue{background:var(--blue-wash);color:var(--blue)}
    table{width:100%;margin:18px 0;border-collapse:collapse;font-size:13px}th,td{padding:12px 10px;border-bottom:1px solid var(--line);text-align:left;vertical-align:top}th{color:#8a8a82;font-size:10px;letter-spacing:.08em;text-transform:uppercase}td{color:var(--muted)}td:first-child{color:var(--ink);font-weight:650}.toc{position:sticky;top:96px;align-self:start;padding-top:43px}.toc p{font-size:11px;font-weight:800;letter-spacing:.09em;text-transform:uppercase}.toc a{display:block;padding:4px 0;text-decoration:none;color:#92928a;font-size:12px}.toc a:hover{color:var(--blue)}
    .footer{border-top:1px solid var(--line);padding:30px 0;color:#8b8b83;font-size:12px}.footer-inner{max-width:1240px;margin:auto;padding:0 28px;display:flex;justify-content:space-between;gap:20px}.footer a{color:var(--muted);text-decoration:none;margin-left:16px}
    @media(max-width:1000px){.layout{grid-template-columns:190px minmax(0,1fr);gap:38px}.toc{display:none}}@media(max-width:720px){.top-inner{padding:0 18px}.top-label,.top-links>a:not(.start){display:none}.layout{display:block;padding:0 20px}.side{position:static;padding:22px 0 0;display:flex;gap:16px;overflow:auto;border-bottom:1px solid var(--line)}.side-label{display:none}.side a{flex:none;padding:8px 0 12px}main{padding:48px 0 80px}.hero h1{font-size:2.8rem}.quick-choice,.mode-grid,.tool-grid{grid-template-columns:1fr}.footer-inner{display:block;padding:0 20px}.footer-links{margin-top:10px}.footer a{margin:0 15px 0 0}}
  </style>
</head>
<body>
  <header class="top"><div class="top-inner"><a class="brand" href="/">vnsh<i>_</i></a><span class="top-label">Documentation</span><nav class="top-links"><a href="https://github.com/raullenchai/vnsh">GitHub</a><a href="/llms.txt">For Agents</a><a class="start" href="https://account.vnsh.dev">Open vnsh</a></nav></div></header>
  <div class="layout">
    <nav class="side" aria-label="Documentation"><div class="side-label">Start here</div><a href="#overview">Overview</a><a href="#quickstart">Quickstart</a><a href="#modes">Choose a mode</a><div class="side-label">Use vnsh</div><a href="#cli">CLI</a><a href="#mcp">AI Agents &amp; MCP</a><a href="#links">Links &amp; permissions</a><div class="side-label">Understand</div><a href="#versions">Versions &amp; conflicts</a><a href="#security">Security model</a><a href="#reference">Reference</a></nav>
    <main>
      <div class="hero" id="overview"><div class="eyebrow">vnsh documentation</div><h1>Give every Agent the context it needs.</h1><p>vnsh is a shared knowledge layer for people and AI Agents. Keep durable project knowledge in Account Artifacts, or make a temporary encrypted handoff with an Incognito Artifact.</p><div class="quick-choice"><a class="choice primary" href="#quickstart"><b>Start with an Account Workspace →</b><span>Permanent, organized knowledge for ongoing work.</span></a><a class="choice" href="#modes"><b>Share something privately →</b><span>No account, host-blind encryption, automatic expiry.</span></a></div></div>
      <section id="quickstart"><span class="section-kicker">Quickstart</span><h2>Your first shared Workspace</h2><p>This is the shortest path from a new account to useful Agent collaboration.</p><div class="steps"><div class="step"><div><b>Sign in and create a Workspace</b><p>Use a Workspace for one project, team, or long-running goal.</p></div></div><div class="step"><div><b>Connect your CLI or Agent</b><p>Approve <code>vn login</code>, or create a revocable token for MCP and CI.</p></div></div><div class="step"><div><b>Create an Artifact</b><p>Store the plan, research, decision log, or handoff that should survive the current chat.</p></div></div><div class="step"><div><b>Give another Agent the link</b><p>The link carries document-level authority. The human chooses who receives it and reviews what changes.</p></div></div></div><pre><code>npm install -g vnsh\nvn login\nvn --artifact project-brief.md</code></pre><div class="note"><strong>No Agent identity system is required.</strong> Today, the human controls access by handing an Agent the appropriate Artifact or capability link.</div></section>
      <section id="modes"><span class="section-kicker">Mental model</span><h2>Two modes, two different promises</h2><p>Choose based on how long the knowledge matters and whether vnsh may process its plaintext.</p><div class="mode-grid"><article class="mode"><span class="badge blue">Recommended for teams</span><h3>Account Artifact</h3><p><strong>Permanent and organized.</strong> Lives inside an account Workspace, supports discovery and retained versions, and is readable by vnsh so authorized people and Agents can collaborate.</p></article><article class="mode"><span class="badge">Private handoff</span><h3>Incognito Artifact</h3><p><strong>Temporary and host-blind.</strong> Encrypted before upload. The key stays in the URL fragment and vnsh stores ciphertext it cannot decrypt.</p></article></div><table><thead><tr><th></th><th>Account</th><th>Incognito</th></tr></thead><tbody><tr><td>Lifetime</td><td>Until you delete it</td><td>24 hours by default; up to 7 days</td></tr><tr><td>Organization</td><td>Workspaces and library</td><td>Link only</td></tr><tr><td>Service can read content</td><td>Yes</td><td>No</td></tr><tr><td>Best for</td><td>Ongoing shared knowledge</td><td>Sensitive or one-off handoffs</td></tr></tbody></table></section>
      <section id="cli"><span class="section-kicker">CLI</span><h2>Use vnsh from the terminal</h2><p>The <code>vn</code> command accepts files or stdin. Once logged in, new Workspaces and Artifacts are permanent.</p><pre><code>curl -sL vnsh.dev/i | sh\nvn login\n\n# Create from a file\nvn --artifact report.md\n\n# Create from command output\nnpm test 2&gt;&amp;1 | vn\n\n# Read and update an encrypted workspace\nvn read "&lt;full-url&gt;"\nvn write "&lt;edit-url&gt;" updated.md</code></pre><h3>Account commands</h3><table><tbody><tr><td><code>vn login</code></td><td>Approve this device in a browser.</td></tr><tr><td><code>vn whoami</code></td><td>Show the connected account.</td></tr><tr><td><code>vn logout</code></td><td>Revoke the credential and remove it locally.</td></tr></tbody></table><p>For non-interactive environments, create a token in your account and set <code>VNSH_TOKEN</code>. It overrides the locally saved login.</p></section>
      <section id="mcp"><span class="section-kicker">AI Agents</span><h2>Connect through MCP</h2><p>The MCP server gives compatible Agents first-class create, list, read, update, history, restore, and renew tools.</p><pre><code>claude mcp add vnsh -- npx -y vnsh-mcp@1.8.2</code></pre><p>For Cursor, Cline, Windsurf, OpenHands, or another MCP client:</p><pre><code>{"vnsh":{"command":"npx","args":["-y","vnsh-mcp@1.8.2"],\n"env":{"VNSH_TOKEN":"your-token"}}}</code></pre><div class="warning note"><strong>Treat the MCP process as trusted local software.</strong> It sees plaintext before encryption. Pin the version if you review the code that handles your content.</div><h3>Make Agents actually use it</h3><p>Installation alone does not create a habit. Add a short project rule to <code>AGENTS.md</code>, <code>CLAUDE.md</code>, or your Agent's project instructions:</p><pre><code>When work should carry over to another Agent, session, or person,\nput it in a vnsh Artifact and share the link instead of pasting it.</code></pre></section>
      <section id="links"><span class="section-kicker">Permissions</span><h2>The link determines what the recipient can do</h2><table><thead><tr><th>Link</th><th>Meaning</th></tr></thead><tbody><tr><td><code>/artifact/{id}#w=…</code></td><td>Encrypted rendered Artifact; read and write.</td></tr><tr><td><code>/w/{id}#w=…</code></td><td>Encrypted Workspace; read and write.</td></tr><tr><td><code>/w/{id}#r=…</code></td><td>Encrypted Workspace; read only.</td></tr><tr><td><code>account.vnsh.dev/c/{token}</code></td><td>One Account Artifact; read or edit according to the capability.</td></tr><tr><td><code>vnshcontent.dev/p/{id}</code></td><td>Public plaintext; readable by any ordinary HTTP client.</td></tr></tbody></table><div class="note"><strong>Share the full URL.</strong> For encrypted links, everything after <code>#</code> contains the client-side key. If it is omitted, the recipient cannot decrypt the document.</div><p>Capability links and edit links are bearer credentials. Send a read-only link unless the recipient needs to change the document.</p></section>
      <section id="versions"><span class="section-kicker">Collaboration</span><h2>Updates never silently overwrite each other</h2><p>Every mutable document has a version. Writers use the version they read as a precondition. If another Agent writes first, vnsh returns a conflict instead of discarding either person's work.</p><div class="steps"><div class="step"><div><b>Read the latest version</b><p>Keep its version number or ETag.</p></div></div><div class="step"><div><b>Write with that version</b><p>The update succeeds only if the document is still current.</p></div></div><div class="step"><div><b>Merge on conflict</b><p>Re-read the current content, combine the work, and retry.</p></div></div></div><p>Account Artifacts retain immutable versions. Restoring an older version creates a new latest version, so history remains intact.</p></section>
      <section id="security"><span class="section-kicker">Security</span><h2>Know where the trust boundary is</h2><div class="tool-grid"><article class="tool"><h3>Incognito</h3><p>Encryption and decryption happen in the browser, CLI, extension, or MCP client. The service stores ciphertext and never receives the fragment key.</p></article><article class="tool"><h3>Account</h3><p>Authentication controls permanent storage and library access. Account Artifact content is service-readable by design to support simple human–Agent collaboration.</p></article></div><p>All mutable writes are conflict-protected. Account tokens are revocable. Encrypted read-only links cannot be turned back into edit links. Public documents use a separate content domain and are served with a sandbox policy.</p><div class="warning note"><strong>Lost encrypted keys cannot be recovered.</strong> An account records ownership metadata, not the secret in an encrypted URL fragment. Keep the complete link.</div></section>
      <section id="reference"><span class="section-kicker">Reference</span><h2>Go deeper when you need to</h2><div class="tool-grid"><a class="choice" href="/llms.txt"><b>Agent protocol →</b><span>Complete machine-readable setup and cryptographic protocol.</span></a><a class="choice" href="https://github.com/raullenchai/vnsh/blob/main/docs/api.md"><b>HTTP API →</b><span>Endpoints, headers, responses, and errors.</span></a><a class="choice" href="https://github.com/raullenchai/vnsh/blob/main/docs/cli.md"><b>CLI reference →</b><span>All commands, flags, and terminal workflows.</span></a><a class="choice" href="https://github.com/raullenchai/vnsh/blob/main/docs/mcp.md"><b>MCP reference →</b><span>Tools, configuration, permissions, and clients.</span></a></div></section>
    </main>
    <aside class="toc"><p>On this page</p><a href="#quickstart">Quickstart</a><a href="#modes">Two modes</a><a href="#cli">CLI</a><a href="#mcp">MCP</a><a href="#links">Permissions</a><a href="#versions">Versions</a><a href="#security">Security</a></aside>
  </div>
  <footer class="footer"><div class="footer-inner"><span>vnsh · Shared knowledge for people and AI Agents</span><span class="footer-links"><a href="/">Home</a><a href="/privacy">Privacy</a><a href="https://github.com/raullenchai/vnsh">GitHub</a></span></div></footer>
</body>
</html>`;
